In [1]:
import numpy as np

In [45]:
x = np.random.normal(size=[3,4,2])

In [46]:
 x

array([[[-1.60811085,  0.9597969 ],
        [-0.19699766,  0.02856959],
        [ 0.70326806, -0.39994452],
        [ 0.34165802, -0.64819811]],

       [[ 0.33220675,  1.47791645],
        [ 0.33145274, -0.07523523],
        [-0.69906821, -0.05147659],
        [-0.21131851, -0.0042635 ]],

       [[ 0.51274604,  1.29100182],
        [-1.61634049, -0.57664837],
        [-1.00699327, -0.81564695],
        [ 0.63594683,  0.08394831]]])

In [47]:
np.argmax(x)

9

In [48]:
np.argmin(x)

18

In [49]:
x.reshape(-1)

array([-1.60811085,  0.9597969 , -0.19699766,  0.02856959,  0.70326806,
       -0.39994452,  0.34165802, -0.64819811,  0.33220675,  1.47791645,
        0.33145274, -0.07523523, -0.69906821, -0.05147659, -0.21131851,
       -0.0042635 ,  0.51274604,  1.29100182, -1.61634049, -0.57664837,
       -1.00699327, -0.81564695,  0.63594683,  0.08394831])

In [50]:
np.argmax(x,axis=0)

array([[2, 1],
       [1, 0],
       [0, 1],
       [2, 2]])

In [51]:
np.argmin(x,axis=0)

array([[0, 0],
       [2, 2],
       [2, 2],
       [1, 0]])

In [52]:
np.argmax(x,axis=1)

array([[2, 0],
       [0, 0],
       [3, 0]])

In [53]:
np.argmin(x,axis=1)

array([[0, 3],
       [2, 1],
       [1, 2]])

In [54]:
np.argmax(x,axis=2)

array([[1, 1, 0, 0],
       [1, 0, 1, 1],
       [1, 1, 1, 0]])

In [55]:
np.argmin(x,axis=2)

array([[0, 0, 1, 1],
       [0, 1, 0, 0],
       [0, 0, 0, 1]])