In [1]:
import tensorflow as tf
import numpy as np

In [5]:
x = np.random.uniform(size=[2,3,4])

In [19]:
print x.shape

(2, 3, 4)


In [14]:
print '-----axis {}------'.format(0)
print x
print x.max(axis=0)
print x.argmax(axis=0)

-----axis0------
[[ 0.48124879  0.37162346  0.27396401  0.78824639]
 [ 0.80874922  0.8655116   0.75741596  0.4548242 ]
 [ 0.29287075  0.60090552  0.95177836  0.39707682]]
[[1 1 1 0]
 [0 0 1 0]
 [1 0 0 0]]


In [15]:
print '-----axis {}------'.format(1)
print x
print x.max(axis=1)
print x.argmax(axis=1)

-----axis 1------
[[ 0.80874922  0.8655116   0.95177836  0.78824639]
 [ 0.75190736  0.76076012  0.75741596  0.60247256]]
[[1 1 2 0]
 [1 1 1 0]]


In [18]:
print '-----axis {}------'.format(2)
print x
print 
print x.max(axis=2)
print 
print x.argmax(axis=2)

-----axis 2------
[[[ 0.03048706  0.11668049  0.09063453  0.78824639]
  [ 0.80874922  0.8655116   0.36825527  0.4548242 ]
  [ 0.04724699  0.60090552  0.95177836  0.39707682]]

 [[ 0.48124879  0.37162346  0.27396401  0.60247256]
  [ 0.75190736  0.76076012  0.75741596  0.11845325]
  [ 0.29287075  0.21288954  0.32252199  0.37199063]]]

[[ 0.78824639  0.8655116   0.95177836]
 [ 0.60247256  0.76076012  0.37199063]]

[[3 1 2]
 [3 1 3]]


In [37]:
y = tf.constant(tf.random_normal(shape=[2,3,4]).eval(),name='y',shape=[2,3,4])

In [38]:
sess = tf.InteractiveSession()

In [40]:
y.eval()

array([[[ 1.78746164,  1.24596357, -0.60129839,  0.97121161],
        [-1.2586261 ,  0.96160638,  1.64465499, -0.56369293],
        [ 0.95138705, -0.21225823,  0.10086749,  0.27445689]],

       [[ 0.51522624,  0.74777263,  0.40712735, -0.04982341],
        [ 0.0845392 ,  0.2283259 , -0.19035283,  1.77780521],
        [-1.62168801,  0.8783884 ,  1.51146531, -0.34187347]]], dtype=float32)

In [41]:
print '-----axis {}------'.format(2)
print y.eval()
print 
print tf.reduce_max(y,axis=2).eval()
print 
print tf.argmax(y,axis=2).eval()

-----axis 2------
[[[ 1.78746164  1.24596357 -0.60129839  0.97121161]
  [-1.2586261   0.96160638  1.64465499 -0.56369293]
  [ 0.95138705 -0.21225823  0.10086749  0.27445689]]

 [[ 0.51522624  0.74777263  0.40712735 -0.04982341]
  [ 0.0845392   0.2283259  -0.19035283  1.77780521]
  [-1.62168801  0.8783884   1.51146531 -0.34187347]]]

[[ 1.78746164  1.64465499  0.95138705]
 [ 0.74777263  1.77780521  1.51146531]]

[[0 2 0]
 [1 3 2]]


In [43]:
print '-----axis {}------'.format(0)
print y.eval()
print 
print tf.reduce_max(y,axis=0).eval()
print 
print tf.argmax(y,axis=0).eval()

-----axis 0------
[[[ 1.78746164  1.24596357 -0.60129839  0.97121161]
  [-1.2586261   0.96160638  1.64465499 -0.56369293]
  [ 0.95138705 -0.21225823  0.10086749  0.27445689]]

 [[ 0.51522624  0.74777263  0.40712735 -0.04982341]
  [ 0.0845392   0.2283259  -0.19035283  1.77780521]
  [-1.62168801  0.8783884   1.51146531 -0.34187347]]]

[[ 1.78746164  1.24596357  0.40712735  0.97121161]
 [ 0.0845392   0.96160638  1.64465499  1.77780521]
 [ 0.95138705  0.8783884   1.51146531  0.27445689]]

[[0 0 1 0]
 [1 0 0 1]
 [0 1 1 0]]


In [44]:
print '-----axis {}------'.format(1)
print y.eval()
print 
print tf.reduce_max(y,axis=1).eval()
print 
print tf.argmax(y,axis=1).eval()

-----axis 1------
[[[ 1.78746164  1.24596357 -0.60129839  0.97121161]
  [-1.2586261   0.96160638  1.64465499 -0.56369293]
  [ 0.95138705 -0.21225823  0.10086749  0.27445689]]

 [[ 0.51522624  0.74777263  0.40712735 -0.04982341]
  [ 0.0845392   0.2283259  -0.19035283  1.77780521]
  [-1.62168801  0.8783884   1.51146531 -0.34187347]]]

[[ 1.78746164  1.24596357  1.64465499  0.97121161]
 [ 0.51522624  0.8783884   1.51146531  1.77780521]]

[[0 0 1 0]
 [0 2 2 1]]
