In [1]:
import tensorflow as tf

In [41]:
x = tf.random_uniform(shape=[3,4,2])

In [42]:
sess = tf.InteractiveSession()

In [43]:
x.eval()

array([[[ 0.1368432 ,  0.56424594],
        [ 0.82957327,  0.82669592],
        [ 0.91055119,  0.63324547],
        [ 0.11208808,  0.67680848]],

       [[ 0.29649723,  0.4528873 ],
        [ 0.8606751 ,  0.90733027],
        [ 0.64761436,  0.52643108],
        [ 0.87306941,  0.21759367]],

       [[ 0.23227417,  0.85689187],
        [ 0.55590141,  0.93081796],
        [ 0.09919178,  0.14500809],
        [ 0.47996163,  0.35458314]]], dtype=float32)

In [57]:
tf.argmax(x,axis=0).eval()

array([[1, 1],
       [1, 2],
       [1, 2],
       [1, 2]])

In [58]:
tf.argmin(x,axis=0).eval()

array([[0, 0],
       [0, 1],
       [0, 0],
       [1, 0]])