In [148]:
import tensorflow as tf

sess = tf.Session()
writer = tf.summary.FileWriter('./graphs', sess.graph) 

In [149]:
a = tf.constant(4.9,name = 'a')
b = tf.constant(5.0,dtype=tf.float32,name='b')

In [130]:
a,b

(<tf.Tensor 'a:0' shape=() dtype=float32>,
 <tf.Tensor 'b:0' shape=() dtype=float32>)

In [140]:
sess.run([a,b])

[4.9000001, 5.0]

In [132]:
c = a + b
sess.run(c)

9.8999996

In [133]:
c = a * b

In [135]:
sess.run(c)


In [141]:
print sess.graph.as_graph_def()

node {
  name: "Const"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_FLOAT
        tensor_shape {
        }
        float_val: 4.90000009537
      }
    }
  }
}
node {
  name: "Const_1"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_FLOAT
        tensor_shape {
        }
        float_val: 5.0
      }
    }
  }
}
node {
  name: "add"
  op: "Add"
  input: "Const"
  input: "Const_1"
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
}
node {
  name: "mul"
  op: "Mul"
  input: "Const"
  input: "Const_1"
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
}
node {
  name: "Variable/initial_value"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_FLOA

In [65]:

W = tf.Variable([.3],dtype=tf.float32)
b = tf.Variable([-.3],dtype=tf.float32)
x = tf.placeholder(tf.float32)

init = tf.global_variables_initializer()
sess.run(init)



In [66]:
linear_model = W*x + b
linear_model

<tf.Tensor 'add_5:0' shape=<unknown> dtype=float32>

In [67]:
sess.run(linear_model,feed_dict={x:[1.,2.]})

array([ 0.        ,  0.30000001], dtype=float32)

In [68]:
y = tf.placeholder(tf.float32)

square = tf.square(y-linear_model)
loss = tf.reduce_sum(square)


In [69]:
sess.run(loss,feed_dict={x:[1.,2.],y:[3.,4.]})

22.690001

Change value of variables 

In [70]:
fixW = tf.assign(W,[-1.])
fixb = tf.assign(b,[1.])

sess.run([fixW,fixb])

[array([-1.], dtype=float32), array([ 1.], dtype=float32)]

In [71]:
sess.run(loss,feed_dict={x:[1.,3.],y:[3.,4.]})

45.0

In [72]:
sess.run(linear_model,feed_dict={x:[1.,3.],y:[3.,4.]})

array([ 0., -2.], dtype=float32)

In [73]:
optimizer = tf.train.GradientDescentOptimizer(0.01)
train = optimizer.minimize(loss)

In [86]:
sess.run(init)
for i in range(1000):
    sess.run(train,feed_dict={x:[1.,2.],y:[3.,4.]})

In [87]:
print(sess.run([W, b]))

[array([ 1.04494095], dtype=float32), array([ 1.92728412], dtype=float32)]


In [88]:
curr_W, curr_b, curr_loss = sess.run([W, b, loss], {x: [1.,2.], y: [3.,4.]})

In [89]:
curr_W, curr_b, curr_loss

(array([ 1.04494095], dtype=float32),
 array([ 1.92728412], dtype=float32),
 0.0010661164)

Use Interactive session if you dont want to pass sess object

In [90]:
sess = tf.InteractiveSession()

In [91]:
a = tf.constant([4.], dtype = tf.float32)
b = tf.constant([5.], dtype = tf.float32)
c= a+b

In [92]:
c.eval()

array([ 9.], dtype=float32)

In [93]:
sess.run(c)

array([ 9.], dtype=float32)

In [110]:


g1= tf.get_default_graph()


with g1.as_default():
    a = tf.constant(10.0, dtype = tf.float32)

with tf.Session(graph = g1) as sess:
    
    print sess.run(a)
    
    
    

g2= tf.Graph()


with g2.as_default():
    a = tf.constant(100.0, dtype = tf.float32)

with tf.Session(graph = g2) as sess:
    writer = tf.summary.FileWriter('./graphs', sess.graph) 
    print sess.run(a)


10.0
100.0


In [111]:
writer

In [112]:
with tf.Session() as sess:
    writer = tf.summary.FileWriter('./graphs', sess.graph) 
    a = tf.constant([1.],dtype=tf.float32)
    b = tf.constant([1.],dtype=tf.float32)
    c = a +b
    
    print sess.run(c)




[ 2.]


In [126]:
sess.close()

In [127]:
writer.close()

In [144]:
tf.Graph().is_feedable(c)

True

In [151]:
sess.close()
x = tf.Variable(10, name='x')
y = tf.Variable(20, name='y')
sess = tf.Session()
writer = tf.summary.FileWriter('./my_graph', sess.graph)
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    for _ in range(10):
        sess.run(tf.add(x, y)) # someone decides to be clever to save one line of code
